#  convert.py
#  Kristin Albright and Xinyan Xiang
#  10 November 2021
#  create csv files for our database

import csv

# Orginal csv files
grammy_information = "the_grammy_awards.csv"

# csv files generated by this code 
category = "category.csv"
award_year = "award_year.csv"
nominee_award = "nominee_award.csv"
nominee_information = "nominee_information.csv"

# dictionary for 
category_dictionary = {}
award_year_dictionary = {}
nominee_information_dictionary = {}

# Create category.csv with columns: 'id','category_name'
with open(grammy_information, 'r') as grammy_information_file:
    grammy_information_reader = csv.reader(grammy_information_file)
    header = next(grammy_information_reader)
    with open(category, 'w') as category_file:
        category_writer = csv.writer(category_file)
        category_id = 1
        for grammy_information_row in grammy_information_reader:
            category_name = grammy_information_row[4]
            if category_name not in category_dictionary:
                category_writer.writerow([category_id,category_name])
                category_dictionary[category_name] = category_id
                category_id = category_id + 1
        # print(category_dictionary)
    category_file.close()
grammy_information_file.close()

# Create award_year.csv with columns: 'id','year','award_title'
with open(grammy_information, 'r') as grammy_information_file:
    grammy_information_reader = csv.reader(grammy_information_file)
    header = next(grammy_information_reader)
    with open(award_year, 'w') as award_year_file:
        award_year_writer = csv.writer(award_year_file)
        award_year_id = 1
        for grammy_information_row in grammy_information_reader:
            award_title_name = grammy_information_row[1]
            if award_title_name not in award_year_dictionary:
                year = grammy_information_row[0]
                award_year_writer.writerow([award_year_id,year,award_title_name])
                award_year_dictionary[award_title_name] = award_year_id
                award_year_id = award_year_id + 1
        # print(award_year_dictionary)
    award_year_file.close()
grammy_information_file.close()

# Create nominee_information.csv with columns: 'id','nominee_name','artist ','workers','img'
with open(grammy_information, 'r') as grammy_information_file:
    grammy_information_reader = csv.reader(grammy_information_file)
    header = next(grammy_information_reader)
    with open(nominee_information, 'w') as nominee_information_file:
        nominee_information_writer = csv.writer(nominee_information_file)
        nominee_information_id = 1
        for grammy_information_row in grammy_information_reader:
            nominee_name = grammy_information_row[5]
            if nominee_name not in nominee_information_dictionary:
                artist = grammy_information_row[6]
                workers = grammy_information_row[7]
                if artist == "" and workers == "":
                    artist = grammy_information_row[5]
                elif artist == "" and workers != "":
                    artist = workers
                elif workers == "" and artist != "":
                    workers = artist
                img = grammy_information_row[8] 
                nominee_information_writer.writerow([nominee_information_id,nominee_name,artist,workers,img])
                nominee_information_dictionary[nominee_name] = nominee_information_id
                nominee_information_id= nominee_information_id + 1
    nominee_information_file.close()

nominee_information_list = list(nominee_information_dictionary)
category_list = list(category_dictionary)
award_year_list = list(award_year_dictionary) 

# Create nominee_award.csv with columns: 'id','award_year_id','category_id','nominee_id'
with open(grammy_information, 'r') as grammy_information_file:
    grammy_information_reader = csv.reader(grammy_information_file)
    header = next(grammy_information_reader)
    with open(nominee_award, 'w') as nominee_award_file:
        nominee_award_writer = csv.writer(nominee_award_file)
        nominee_award_id = 1
        for grammy_information_row in grammy_information_reader:
            award_year_ID =  award_year_list.index(grammy_information_row[1]) + 1
            category_ID = category_list.index(grammy_information_row[4]) + 1
            nominee_name_ID = nominee_information_list.index(grammy_information_row[5]) + 1
            nominee_award_writer.writerow([nominee_award_id,award_year_ID,category_ID,nominee_name_ID])
            nominee_award_id = nominee_award_id + 1
    nominee_award_file.close()





